- name: Install linstor-affinity to k3s
  hosts: k3s_init
  gather_facts: false
  tasks:
    - name: Check if already installed
      ansible.builtin.raw: ls /var/lib/rancher/k3s/server/manifests/linstor-affinity.yaml
      register: ls_output
      changed_when: false
      ignore_errors: true
      become: true
    - name: Fail if already installed
      ansible.builtin.fail:
        msg: linstor-affinity is already installed
      when: ls_output.rc == 0
    - name: Create linstor-affinity install file
      ansible.posix.synchronize:
        src: "files/linstor-affinity-chart.txt"
        dest: "/tmp/linstor-affinity.yaml"
    - name: Set permissions linstor-affinity install file
      ansible.builtin.raw: chmod 600 /tmp/linstor-affinity.yaml
      register: chmod_output
      changed_when: false
    - name: Set owner linstor-affinity install file
      ansible.builtin.raw: chown root:root /tmp/linstor-affinity.yaml
      register: chown_output
      changed_when: false
      become: true
    - name: Move to k3s manifests
      ansible.builtin.raw: "[ ! -f /var/lib/rancher/k3s/server/manifests/linstor-affinity.yaml ] && mv /tmp/linstor-affinity.yaml /var/lib/rancher/k3s/server/manifests/linstor-affinity.yaml"
      register: mv_output
      changed_when: mv_output.rc == 0
      ignore_errors: true
      become: true
