- name: Init k3s cluster initial host
  hosts: k3s_init
  gather_facts: false
  tasks:
   - name: Check if already installed
     ansible.builtin.raw: ls /etc/rancher/k3s/k3s.yaml
     register: ls_output
     changed_when: false
   - name: Fail if already installed
     ansible.builtin.fail:
      msg: k3s is already installed
     when: ls_output.rc == 0
   - name: Create new cluster master node
     ansible.builtin.raw: curl -sfL https://get.k3s.io | sh -s - --secrets-encryption --token "{{ k3s_token }}" --tls-san "{{ tls_san }}" --cluster-init
     register: k3s_output
     changed_when: true
   - name: Debug initial k3s cluster init
     ansible.builtin.debug:
      var: k3s_output.stdout_lines
      verbosity: 0

- name: Init all k3s cluster hosts
  hosts: k3s_client
  gather_facts: false
  tasks:
   - name: Check if already installed
     ansible.builtin.raw: ls /etc/rancher/k3s/k3s.yaml
     register: ls_output
     changed_when: false
   - name: Fail if already installed
     ansible.builtin.fail:
      msg: k3s is already installed
     when: ls_output.rc == 0
   - name: Add other nodes to cluster
     ansible.builtin.raw: curl -sfL https://get.k3s.io | sh -s - --secrets-encryption --token "{{ k3s_token }}" --tls-san "{{ tls_san }}" --server https://"{{ init_node_ip }}":6443
     register: k3s_output
     changed_when: true
   - name: Debug all k3s cluster init
     ansible.builtin.debug:
      var: k3s_output.stdout_lines
      verbosity: 0
